repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Используемая версия pre-commit-hooks
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Используемая версия black
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.6.2  # Используемая версия pre-commit
    hooks:
      - id: check-commit-message
        args:
          - --pattern
          - ^TF[0-9]+:.+
